export const dashboardMetrics = {
  liveQueue: 128,
  slaRisk: 7,
  manualReview: 24,
  teamLoad: "82%",
};

export const jobs = [
  {
    id: "JOB-4821",
    company: "Aster Retail Pvt Ltd",
    status: "Completed",
    invoices: 132,
    amount: 482000,
    startedAt: "2026-07-07T08:25:00+05:30",
    updatedAt: "2026-07-07T09:02:00+05:30",
    owner: "Aarav Mehta",
    priority: "Normal",
    source: "Vendor CSV",
    confidence: "99.1%",
    summary: "All invoices matched automatically and moved to final reconciliation.",
    timeline: [
      { label: "Batch uploaded", at: "08:25 AM", state: "done" },
      { label: "Column mapping confirmed", at: "08:32 AM", state: "done" },
      { label: "OCR and validation completed", at: "08:48 AM", state: "done" },
      { label: "Reconciliation exported", at: "09:02 AM", state: "done" },
    ],
  },
  {
    id: "JOB-4819",
    company: "Northwind Traders",
    status: "Review",
    invoices: 48,
    amount: 169800,
    startedAt: "2026-07-07T09:10:00+05:30",
    updatedAt: "2026-07-07T09:38:00+05:30",
    owner: "Mira Kapoor",
    priority: "High",
    source: "Email import",
    confidence: "91.8%",
    summary: "Tax breakdown is inconsistent on 6 rows and vendor GST numbers need confirmation.",
    timeline: [
      { label: "Files imported", at: "09:10 AM", state: "done" },
      { label: "Validation flagged exceptions", at: "09:24 AM", state: "done" },
      { label: "Assigned for manual review", at: "09:38 AM", state: "active" },
      { label: "Awaiting approval", at: "Pending", state: "pending" },
    ],
  },
  {
    id: "JOB-4816",
    company: "Zenith Logistics",
    status: "Processing",
    invoices: 211,
    amount: 324500,
    startedAt: "2026-07-07T09:42:00+05:30",
    updatedAt: "2026-07-07T10:04:00+05:30",
    owner: "Rohan Iyer",
    priority: "Normal",
    source: "SFTP sync",
    confidence: "96.5%",
    summary: "The batch is in extraction and GST validation with no blocking errors yet.",
    timeline: [
      { label: "Batch received", at: "09:42 AM", state: "done" },
      { label: "Extraction in progress", at: "10:04 AM", state: "active" },
      { label: "Validation queue", at: "Next", state: "pending" },
      { label: "Posting to invoices", at: "Pending", state: "pending" },
    ],
  },
  {
    id: "JOB-4812",
    company: "BluePeak Pharma",
    status: "Queued",
    invoices: 86,
    amount: 245900,
    startedAt: "2026-07-07T10:08:00+05:30",
    updatedAt: "2026-07-07T10:08:00+05:30",
    owner: "Diya Sharma",
    priority: "Low",
    source: "Manual upload",
    confidence: "Pending",
    summary: "Waiting for an available validation worker before parsing starts.",
    timeline: [
      { label: "Batch uploaded", at: "10:08 AM", state: "done" },
      { label: "Queued for parsing", at: "10:08 AM", state: "active" },
      { label: "Validation", at: "Pending", state: "pending" },
      { label: "Review routing", at: "Pending", state: "pending" },
    ],
  },
];

export const invoices = [
  {
    id: "INV-1048",
    vendor: "Apex Office Supplies",
    customer: "Aster Retail Pvt Ltd",
    date: "2026-07-01",
    dueDate: "2026-07-21",
    amount: 48200,
    tax: 8676,
    status: "Matched",
    matchScore: "99%",
    jobId: "JOB-4821",
    method: "CSV import",
    paymentStatus: "Ready to export",
    notes: "Vendor GST and PO references matched automatically.",
  },
  {
    id: "INV-1049",
    vendor: "Northwind Traders",
    customer: "Northwind Traders",
    date: "2026-07-01",
    dueDate: "2026-07-18",
    amount: 16980,
    tax: 3056,
    status: "Review",
    matchScore: "92%",
    jobId: "JOB-4819",
    method: "Email import",
    paymentStatus: "Pending review",
    notes: "GST number format mismatch on 2 rows in the source batch.",
  },
  {
    id: "INV-1050",
    vendor: "BluePeak Pharma",
    customer: "BluePeak Pharma",
    date: "2026-07-02",
    dueDate: "2026-07-23",
    amount: 124500,
    tax: 22410,
    status: "Mapped",
    matchScore: "97%",
    jobId: "JOB-4812",
    method: "Manual upload",
    paymentStatus: "Awaiting validation",
    notes: "Line items mapped cleanly; validation has not run yet.",
  },
  {
    id: "INV-1051",
    vendor: "Zenith Logistics",
    customer: "Zenith Logistics",
    date: "2026-07-02",
    dueDate: "2026-07-20",
    amount: 32450,
    tax: 5841,
    status: "Processing",
    matchScore: "96%",
    jobId: "JOB-4816",
    method: "SFTP sync",
    paymentStatus: "In processing",
    notes: "The document is in active extraction and duplicate checks.",
  },
  {
    id: "INV-1052",
    vendor: "Mercury Components",
    customer: "Aster Retail Pvt Ltd",
    date: "2026-07-03",
    dueDate: "2026-07-27",
    amount: 76500,
    tax: 13770,
    status: "Mismatch",
    matchScore: "83%",
    jobId: "JOB-4819",
    method: "Email import",
    paymentStatus: "Blocked",
    notes: "Invoice total does not match line-item sum and needs finance review.",
  },
];

export const reports = [
  {
    id: "REP-071",
    title: "Weekly Processing Summary",
    period: "01 Jul - 07 Jul",
    generatedAt: "2026-07-07",
    owner: "Ops Analytics",
    format: "CSV + PDF",
    status: "Ready",
    insight: "Processing throughput is up 18% with review volume stable.",
  },
  {
    id: "REP-072",
    title: "Mismatch Recovery Report",
    period: "Q2 FY26",
    generatedAt: "2026-07-06",
    owner: "Finance Control",
    format: "PDF",
    status: "Shared",
    insight: "Recovered revenue estimate is ₹8.4L from mismatch detection.",
  },
  {
    id: "REP-073",
    title: "Vendor SLA Breakdown",
    period: "Jun 2026",
    generatedAt: "2026-07-05",
    owner: "Vendor Ops",
    format: "Dashboard export",
    status: "Draft",
    insight: "Three vendors are consistently missing tax metadata in uploads.",
  },
];

export const profile = {
  name: "Priya Nair",
  role: "Operations Lead",
  email: "priya.nair@cleartax.example",
  phone: "+91 98765 43210",
  team: "Invoice Operations",
  location: "Bengaluru",
  bio: "Leads upload quality, exception handling, and reporting for large invoice batches.",
};

export const settingsGroups = [
  {
    title: "Notifications",
    items: [
      { label: "Job failure alerts", value: "Enabled" },
      { label: "Daily summary email", value: "08:30 AM" },
      { label: "SLA breach escalation", value: "Immediate" },
    ],
  },
  {
    title: "Upload Rules",
    items: [
      { label: "Allowed file types", value: "CSV, XLSX, ZIP" },
      { label: "Duplicate detection", value: "Strict" },
      { label: "Auto column mapping", value: "Enabled" },
    ],
  },
];

export function getJobById(jobId) {
  return jobs.find((job) => job.id === jobId);
}

export function getInvoiceById(invoiceId) {
  return invoices.find((invoice) => invoice.id === invoiceId);
}
